- id: '1576489625988'
  alias: Turn on lights when i arrive home in the dark
  description: ''
  trigger:
  - entity_id: person.michel_van_hoof
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - entity_id: light.enterance_light
    service: light.turn_on
  - entity_id: light.hallway_lights
    service: light.turn_on
- id: '1576489962101'
  alias: Turn on lights when i am home and it is getting dark
  description: ''
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  condition:
  - condition: state
    entity_id: person.michel_van_hoof
    state: home
  action:
  - alias: ''
    data: {}
    entity_id: light.kitchen_coffee_area
    service: light.turn_on
  - entity_id: switch.living_tv_light
    service: switch.turn_on
  - entity_id: switch.living_couch_window
    service: switch.turn_on
  - entity_id: switch.dinning_table
    service: switch.turn_on
- id: '1582727666736'
  alias: Turn on kids week when their tablets arrive
  description: ''
  trigger:
  - entity_id: device_tracker.nicholas_galaxya
    from: not_home
    platform: state
    to: Home
  - entity_id: device_tracker.alexandra_galaxya
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.kids_week
    state: 'off'
  action:
  - entity_id: input_boolean.kids_week
    service: input_boolean.turn_on
- id: '1582727988790'
  alias: Inform dad that kids week has started
  description: ''
  trigger:
  - entity_id: input_boolean.kids_week
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Kids week just started
      title: Kids week
    service: notify.mobile_app_michel_s10plus
  - data:
      message: Kids week just started
      title: Kids week
    service: persistent_notification.create
  - data:
      message: notifynotify Kids week just started
      title: notifynotify Kids week
    service: notify.notify
- id: '1582759366549'
  alias: Master Bedroom Wake-up Routine when alarm is set
  description: ''
  trigger:
  - platform: template
    value_template: '{{ (states.input_datetime.master_bedroom_alarm_clock_time.attributes[''timestamp'']
      | timestamp_custom(''%H:%M'', False) ) == ( states.sensor.time.state ) }}'
  condition:
  - condition: state
    entity_id: input_boolean.master_bedroom_alarm_enabled
    state: 'on'
  action:
  - data:
      brightness: 255
      transition: 600
    entity_id: light.kitchen_main
    service: light.turn_on
  - data:
      message: Time to get buzzzzzy
      title: Wake Up Asshole
    service: notify.mobile_app_michel_s10plus
- id: '1582759741755'
  alias: Test Slow Increase
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      brightness_pct: 100
      transition: 60
    entity_id: light.living_spots
    service: light.turn_on
