
- id: '1585055307641'
  alias: Comfort - Lights - Turn on lights when it get's dark & Michel is home
  description: ''
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  condition:
  - condition: state
    entity_id: group.inhabitants
    state: home
  action:
  - scene: scene.background_lighting_livingroom
- id: '1585055543752'
  alias: Comfort - Light - Turn on lights when I arrive in the Dark
  description: ''
  trigger:
  - entity_id: person.michel
    platform: state
    to: home
  condition:
  - after: sunset
    after_offset: -00:30
    before: sunrise
    before_offset: +01:00
    condition: sun
  action:
  - data: {}
    entity_id: light.inkomhal_licht
    service: light.turn_on
  - data: {}
    entity_id: light.gang_bureau
    service: light.turn_on
  - scene: scene.background_lighting_livingroom
- id: '1585055949591'
  alias: Comfort - Master Bedroom Alarm - Master Bedroom Wake Up Routine
  description: Alarm Clock voor Master Bedroom
  trigger:
  - platform: template
    value_template: '{{ (states.input_datetime.master_bedroom_alarm_clock_time.attributes[''timestamp'']
      | timestamp_custom(''%H:%M'', False) ) == ( states.sensor.time.state ) }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.michel
      state: home
    - condition: state
      entity_id: input_boolean.master_bedroom_alarm_enabled
      state: 'on'
  action:
  - data:
      entity_id: media_player.master_bedroom_speaker
      message: Ochtend routine gestart
    service: tts.google_translate_say
  - delay: 00:00:30
  - data: {}
    service: script.alarm_clock_master_bedroom_play_music
  - data: {}
    service: script.master_bedroom_wake_up_light
- id: '1585413002072'
  alias: System - Notifications - Restore Notifications from MQTT
  description: When hassio is starting up, read the existing notifications from mqtt
  trigger:
  - platform: mqtt
    topic: home-assistant/home/notifications/persistent/+
  condition:
  - condition: template
    value_template: ' {{ trigger.payload != '''' and state_attr("persistent_notification."
      + trigger.payload_json.notification_id | replace("-","_"),"message") != trigger.payload_json.message
      }}'
  action:
  - data_template:
      title: "{{ trigger.payload_json.title }}\n   message: >-\n     {{ trigger.payload_json.message\
        \ }}\n   notification_id: >-\n     {{ trigger.payload_json.notification_id\
        \ }}"
    service: persistent_notification.create
- id: '1585413111685'
  alias: System - Notifications - Remove Saved notifications on dismiss
  description: ''
  trigger:
  - event_data:
      domain: persistent_notification
      service: dismiss
    event_type: call_service
    platform: event
  condition: []
  action:
  - data_template:
      retain: true
      topic: home-assistant/home/notifications/persistent/{{ trigger.event.data.service_data.notification_id
        }}
    service: mqtt.publish
- id: '1585413304575'
  alias: System - Notifications - Save notifications on Create
  description: ''
  trigger:
  - event_data:
      domain: persistent_notification
      service: create
    event_type: call_service
    platform: event
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.service_data.notification_id != "config_entry_discovery"
      }}'
  action:
  - data_template:
      payload: "{\n           \"notification_id\" : \"{{ trigger.event.data.service_data.notification_id\
        \ }}\",\n           \"title\" : \"{{ trigger.event.data.service_data.title\
        \ }}\",\n           \"message\" : \"{{ trigger.event.data.service_data.message\
        \ }}\"\n         }"
      topic: home-assistant/home/notifications/persistent/{{ trigger.event.data.service_data.notification_id
        }}
    service: mqtt.publish
- id: '1585413492631'
  alias: Chores - Dryer - When dryer is started, clear washing machine chore
  description: When the dryer is started and the washing machine chore is active,
    clear it
  trigger:
  - entity_id: sensor.droogkast_status
    from: 'off'
    platform: state
    to: running
  condition:
  - condition: state
    entity_id: input_boolean.chore_empty_washingmachine
    state: 'on'
  action:
  - data: {}
    entity_id: input_boolean.chore_empty_washingmachine
    service: input_boolean.turn_off
  - data:
      notification_id: home_chores_clear_washingmachine
    service: persistent_notification.dismiss
- id: '1585491830205'
  alias: System - Voice Notifications from MQTT messages
  description: Voice Notifications from MQTT messages
  trigger:
  - platform: mqtt
    topic: home-assistant/notifications/voice/+
  condition: []
  action:
  - data_template:
      value1: '{{ trigger.payload_json.message }}'
    service: script.speech_engine
- id: '1585512654157'
  alias: Notify us from home assistant restarts
  description: ''
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      value1: De huis Assistent wordt gestopt.
    service: script.speech_engine
- id: '1585512728669'
  alias: Home Assistant Start
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      value1: De huis assistent is terug gestart.
    service: script.speech_engine
- id: '1585550911522'
  alias: Comfort - Turn on Night Light for the kids
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.inhabitants
      state: home
    - condition: state
      entity_id: binary_sensor.kids_week
      state: 'on'
  action:
  - data: {}
    entity_id: light.slaapkamer_2_s3
    service: light.turn_on
  - data:
      value1: Het is bijna slaaptijd voor de kinderen. Ik heb hun nachtlampje aangedaan.
    service: script.speech_engine
- id: '1585551035385'
  alias: Comfort - Kids - Turn off night light in the morning
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: state
    entity_id: light.slaapkamer_2_s3
    state: 'on'
  action:
  - data: {}
    entity_id: light.slaapkamer_2_s3
    service: light.turn_off
  - data:
      value1: Ik heb het nachtlampje van de kinderen uit gezet.
    service: script.speech_engine
