- id: '1576489625988'
  alias: Turn on lights when i arrive home in the dark
  description: ''
  trigger:
  - entity_id: person.michel
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - entity_id: light.enterance_light
    service: light.turn_on
  - entity_id: light.hallway_lights
    service: light.turn_on
  - scene: scene.turn_on_relax_lights

- id: '1582727666736'
  alias: Turn on kids week when their tablets arrive
  description: ''
  trigger:
  - entity_id: device_tracker.nicholas_galaxya
    from: not_home
    platform: state
    to: Home
  - entity_id: device_tracker.alexandra_galaxya
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.kids_week
    state: 'off'
  action:
  - entity_id: input_boolean.kids_week
    service: input_boolean.turn_on
- id: '1582727988790'
  alias: Inform dad that kids week has started
  description: ''
  trigger:
  - entity_id: input_boolean.kids_week
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Kids week just started
      title: Kids week
    service: notify.mobile_app_michel_s10plus
  - data:
      id: home_feed_kids_week_started
      message: Kids week just started
      title: Kids week
    service: persistent_notification.create
  - data:
      message: notifynotify Kids week just started
      title: notifynotify Kids week
    service: notify.notify


- id: '1582992007044'
  alias: Vertel me dat de wasmachine klaar is als ik thuis ben
  description: ''
  trigger:
  - entity_id: sensor.washing_machine_status
    for: 00:05
    from: running
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.michel
    state: Home
  action:
  - data:
      entity_id: media_player.living_room
      message: Laundry is done
    service: tts.google_translate_say
  - entity_id: media_player.living_room
    service: media_player.media_previous_track



- id: '1583062395933'
  alias: When Michel is home he wants to be informed
  description: ''
  trigger:
  - platform: mqtt
    topic: home-assistant/notifications/+
  condition:
  - condition: state
    entity_id: person.michel
    state: home
  action:
    data_template:
        title: >-
          {{ trigger.payload_json.title }}
        message: >-
          {{ trigger.payload_json.message }}
    service: notify.mobile_app_michel_s10_plus
- id: '1583064607332'
  alias: When Michel is not home, create a todoist task for events
  description: ''
  trigger:
  - platform: mqtt
    topic: home-assistant/notifications/+
  condition:
  - condition: state
    entity_id: person.michel
    state: not_home
  action:
  - data_template:
      content: '{{ trigger.payload_json.title |string }}'
      due_date_string: Today at 20pm
      labels: home
      priority: 1
      project: Household
    service: todoist.new_task