custom_header:
  compact_mode: true
  kiosk_mode: false
  disable_sidebar: false
  hide_config: false
  hide_help: false
  voice_hide: false
  options_hide: false
  menu_dropdown: true
  indicator_top: true
  chevrons: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
  hide_tabs: 0 to 100
  exceptions:
    - conditions:
        user: Alexandra, Nicholas
      config:
        show_tabs: 
          - 0
          - 5
        default_tab: 5
        header_text: Alexandra Bij Papa
        # For kiosk mode, we need to configure navigation buttons
        #kiosk_mode: true
        hide_config: true
        hide_help: true
        voice_hide: true
        options_hide: true
        disable_sidebar: true
    - conditions:
        user: Michel
      config:
        show_tabs:
          - 0 to 4
          - 6 to 100
    - conditions:
        # user: maykar, Bram Kragten, Ludeeus
        user_agent: Mobile
        media_query: "(max-width: 600px)"
      config:
        #footer_mode: true
        #reverse_button_direction: true
        #reverse_tab_direction: true
        disable_sidebar: true
        voice_hide: true
        options_hide: true
        chevrons: false
        menu_dropdown: true
#Some templates to use further
resources:
  # https://github.com/lukevink/home-assistant-buienradar-forecast-card/blob/master/buien-rain-card.js
  - url: /local/custom_ui/buien-radar/buien-rain-card.js
    type: module

  # https://github.com/maykar/custom-header
  - url: /local/custom_ui/custom-header/custom-header.js
    type: module

  # https://github.com/thomasloven/lovelace-auto-entities
  - url: /local/custom_ui/auto-entities/auto-entities.js
    type: module

    # https://github.com/kalkih/mini-media-player
  - url: /local/custom_ui/mini-media-player/mini-media-player-bundle.js
    type: module

    # https://github.com/gadgetchnnel/lovelace-home-feed-card/
  - type: js
    url: /local/custom_ui/lovelace-home-feed-card/lovelace-home-feed-card.js

    # https://github.com/custom-cards/button-card
  - type: module
    url: /local/custom_ui/button-card/button-card.js

    # https://github.com/thomasloven/lovelace-slider-entity-row
  - type: module
    url: /local/custom_ui/lovelace-slider-entity-row/slider-entity-row.js

    # https://github.com/sbryfcz/harmony-card/
  - type: module
    url: /local/custom_ui/harmony-card/harmony-card.js

    # https://github.com/lukevink/home-assistant-buienradar-forecast-card
  - type: module
    url: /local/custom_ui/buien-rain-card/buien-rain-card.js

    # https://github.com/custom-cards/text-element
  - type: module
    url: /local/custom_ui/text-element/text-element.js

button_card_templates: !include_dir_merge_list lovelace/card_templates/
#Actual start of the main view
title: Van Hoof
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/status.yaml
  - !include lovelace/views/living_area/view.yaml
  - !include lovelace/views/office/office-view.yaml
  - !include lovelace/views/master_bedroom/view-master-bedroom.yaml
  - !include lovelace/views/kids/view-kids.yaml
  - !include lovelace/views/debug/view-debug.yaml  
  - !include lovelace/views/chores.yaml