resources:
  - type: module
    url: /local/atomic_calendar.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /community_plugin/spotify-card/spotify-card.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/harmony-card/harmony-card.js
  - type: module
    url: /community_plugin/flex-horseshoe-card/flex-horseshoe-card.js
  - type: module
    url: /community_plugin/lovelace-animated-background/animated-background.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: js
    url: >-
      https://raw.githubusercontent.com/gadgetchnnel/lovelace-home-feed-card/master/custom_card.json
title: Van Hoof
views:
  - badges: []
    cards:
      - entities:
          - entity: light.kitchen_main
          - entity: light.kitchen_coffee_area
          - entity: light.dinning_spots
          - entity: light.living_spots
          - entity: group.living_relax_lights
        title: Verlichting
        type: entities
      - entity: media_player.spotify_michel_van_hoof
        type: media-control
    path: living
    title: Living
  - badges:
      - entity: sensor.to_xant
      - entity: sensor.home_commute
      - entity: sensor.speedtest_download
      - entity: sensor.speedtest_upload
    cards:
      - card:
          show_header_toggle: false
          show_state: false
          title: Who is home?
          type: glance
        entities:
          - entity: person.michel_van_hoof
            name: Michel
          - entity: person.nicholas_van_hoof
            name: Nicholas
          - entity: person.alexandra_van_hoof
            name: Alexandra
        show_empty: false
        state_filter:
          - home
        type: entity-filter
      - entities:
          - media_player.living_room
          - media_player.living_tv
          - media_player.woonkamer
          - media_player.living_kodi
          - media_player.spotify
        state_filter:
          - playing
        type: entity-filter
      - entities:
          - entity: input_select.chromecast_radio
          - entity: input_select.radio_station
          - entity: script.home_radio
          - entity: input_number.spotify_volume
        show_header_toggle: false
        title: Music
        type: entities
      - card:
          tap_action:
            action: toggle
          title: Lights ON
          type: entities
        entities:
          - light.bathroom_l3
          - light.bathroom_shower_spots
          - light.bathroom_spots
          - light.cv_room
          - light.carport_flowerbed
          - light.carport_main_light
          - light.carport_night_light
          - light.carport_storage_1
          - light.carport_storage_2
          - light.dad_bedroom_spots
          - light.dinning_l2
          - light.dinning_l3
          - light.dinning_spots
          - light.dressing_spots
          - light.enterance_light
          - light.hallway_lights
          - light.kids_bedroom_l2
          - light.kids_bedroom_spots
          - light.kitchen_coffee_area
          - light.kitchen_l3
          - light.kitchen_main
          - light.living_l2
          - light.living_l3
          - light.living_spots
          - light.master_bathroom_l2
          - light.master_bathroom_l3
          - light.master_bathroom_spots
          - light.master_bedroom_l2
          - light.master_bedroom_l3
          - light.master_bedroom_spots
          - light.office_l2
          - light.office_l3
          - light.office_spots
          - light.stairs_0_1
          - light.stairs_1_2
          - light.terrace
          - switch.dad_bedroom_fan
          - switch.dad_bedroom_s1
          - switch.dad_bedroom_s2
          - switch.dad_bedroom_s3
          - switch.dinning_table
          - switch.kids_bedroom_fan
          - switch.kids_bedroom_s1
          - switch.kids_bedroom_s3
          - switch.kids_bedroom_s4
          - switch.kids_bedroom_window_left
          - switch.living_couch_dinning
          - switch.living_couch_window
          - switch.living_tv_light
          - switch.master_bedroom_s1
          - switch.master_bedroom_s2
          - switch.master_bedroom_s3
          - switch.office_desk_left
          - switch.office_library_left
          - switch.office_s2
        show_empty: false
        state_filter:
          - 'on'
        type: entity-filter
      - entities:
          - entity: light.kitchen_main
          - entity: light.kitchen_coffee_area
          - entity: light.dinning_spots
          - entity: light.living_spots
          - entity: group.living_relax_lights
        title: Verlichting
        type: entities
      - entities:
          - entity: sensor.home_commute
          - entity: sensor.to_xant
          - entity: sensor.to_bagaar
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_ping
          - entity: input_boolean.kids_week
        show_header_toggle: false
        title: Quick Info
        type: entities
      - entities:
          - entity: group.living_relax_lights
        show_state: false
        title: Lights
        type: glance
      - cards:
          - card:
              entity: media_player.spotify
              type: media-control
            conditions:
              - entity: media_player.spotify
                state: playing
            type: conditional
        type: vertical-stack
      - entity: sensor.speedtest_download
        max: 300
        min: 0
        name: Download Speed
        severity:
          green: 200
          red: 100
          yellow: 150
        theme: default
        type: gauge
      - entity: input_boolean.kids_week
        hold_action:
          action: more-info
        show_icon: true
        show_name: false
        tap_action:
          action: toggle
        type: entity-button
      - entity: sensor.speedtest_ping
        max: 100
        min: 0
        severity:
          green: 15
          red: 30
          yellow: 20
        theme: default
        type: gauge
      - entities:
          - entity: automation.test_slow_increase
        type: entities
      - aspect_ratio: 50%
        entity: person.alexandra_van_hoof
        image: /local/images/alexandra.jpg
        type: picture-entity
      - type: picture-glance
        image: /local/images/alexandra.jpg
        entities:
          - entity: person.alexandra_van_hoof
          - entity: device_tracker.alexandra_galaxya
        aspect_ratio: 0%
        entity: person.alexandra_van_hoof
        title: Alexandra
      - type: picture-glance
        image: 'https://graph.facebook.com/1276561060/picture?type=large'
        entities:
          - entity: person.michel_van_hoof
          - entity: device_tracker.michel_ipad2
        aspect_ratio: 0%
        title: Michel
        entity: person.michel_van_hoof
    icon: 'mdi:home'
    panel: false
    path: home
    title: Home
  - badges:
      - entity: person.nicholas_van_hoof
      - entity: person.michel_van_hoof
      - entity: person.alexandra_van_hoof
    cards:
      - entities:
          - entity: group.family
        type: glance
      - entities:
          - entity: group.all_lights
        state_filter:
          - 'on'
        type: entity-filter
      - columns: 3
        entities:
          - entity: sensor.sonarr_disk_space
          - entity: sensor.sonarr_queue
          - entity: sensor.sonarr_upcoming
          - entity: sensor.sonarr_wanted
          - entity: sensor.family_sab_queue_count
          - entity: sensor.family_sab_speed
          - entity: sensor.family_sab_status
          - entity: sensor.family_sab_total
        show_icon: true
        show_state: true
        title: TV Show status
        type: glance
      - entities:
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_ping
        title: Internet Speed
        type: glance
      - entities:
          - entity: sensor.freenas_uptime
          - entity: sensor.freenas_1min_load
          - entity: sensor.freenas_5min_load
          - entity: sensor.freenas_15min_load
        title: Nebula
        type: entities
      - entities:
          - entity: remote.living_room_hub
        title: remote
        type: entities
    title: Geek
  - badges:
      - entity: binary_sensor.updater
      - entity: person.michel_van_hoof
      - entity: person.alexandra_van_hoof
      - entity: person.nicholas_van_hoof
      - entity: device_tracker.michel_s8
      - entity: device_tracker.nicholas_galaxya
      - entity: device_tracker.alexandra_galaxya
      - entity: sensor.to_xant
      - entity: sensor.home_commute
      - entity: sensor.speedtest_ping
      - entity: sensor.speedtest_upload
      - entity: sensor.speedtest_download
      - entity: sun.sun
    cards:
      - entity: media_player.living_room
        type: media-control
      - entity: media_player.living_tv
        type: media-control
      - entities:
          - calendar.xylos
          - calendar.family
          - calendar.kalender_venstraat
          - calendar.michel_van_hoof_prive
          - calendar.kalender_lagere_school
          - calendar.todoist
          - calendar.holidays_in_belgium
        title: Kalender
        type: entities
      - entities:
          - light.office_l2
          - light.kids_bedroom_l2
          - light.office_l3
          - light.dad_bedroom_spots
          - light.terrace
          - light.carport_main_light
          - light.dressing_spots
          - light.enterance_light
          - light.carport_night_light
          - light.cv_room
          - light.hallway_lights
          - light.carport_flowerbed
          - light.master_bathroom_spots
          - light.stairs_0_1
          - light.carport_storage_1
          - light.master_bathroom_l2
          - light.stairs_1_2
          - light.carport_storage_2
          - light.master_bathroom_l3
          - light.living_spots
          - light.dinning_spots
          - light.master_bedroom_spots
          - light.living_l2
          - light.dinning_l2
          - light.master_bedroom_l2
          - light.living_l3
          - light.dinning_l3
          - light.master_bedroom_l3
          - light.bathroom_spots
          - light.kitchen_main
          - light.bathroom_shower_spots
          - light.kitchen_coffee_area
          - light.bathroom_l3
          - light.kitchen_l3
          - light.kids_bedroom_spots
          - light.office_spots
        title: Licht
        type: entities
      - entity: media_player.living_kodi
        type: media-control
      - entity: media_player.woonkamer
        type: media-control
      - entities:
          - switch.kids_bedroom_fan
          - switch.kids_bedroom_s1
          - switch.kids_bedroom_window_left
          - switch.kids_bedroom_s3
          - switch.kids_bedroom_s4
          - switch.dad_bedroom_fan
          - switch.dad_bedroom_s1
          - switch.dad_bedroom_s2
          - switch.living_couch_window
          - switch.dad_bedroom_s3
          - switch.living_tv_light
          - switch.master_bedroom_s1
          - switch.living_couch_dinning
          - switch.master_bedroom_s2
          - switch.dinning_table
          - switch.master_bedroom_s3
          - switch.office_desk_left
          - switch.office_s2
          - switch.office_library_left
        title: Schakelaar
        type: entities
      - entity: weather.home
        type: weather-forecast
    path: default_view
    title: Home Test
  - badges: []
    cards:
      - entities:
          - entity: input_select.radio_station
          - entity: input_select.chromecast_radio
          - entity: script.home_radio
        show_header_toggle: false
        title: Radio
        type: entities
      - entity: weather.dark_sky
        theme: Backend-selected
        type: weather-forecast
      - entities:
          - entity: camera.buienradar_loop
        type: entities
      - aspect_ratio: 86%
        camera_image: camera.buienradar_loop
        entity: camera.buienradar_loop
        image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
        type: picture-entity
      - entity: media_player.spotify_michel_van_hoof
        type: media-control
      - content: |-
          {% for note in states.persistent_notification -%}
          Title:{{note}}
          Message: {{state_attr('note','id')}}
          {%- endfor %}
        title: Notifications
        type: markdown
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        entity: light.dinning_spots
        icon_height: 40px
    panel: false
    path: test
    title: Test
  - badges: []
    cards:
      - entity: light.dad_bedroom_spots
        name: Spots
        type: light
      - entity: light.stairs_0_1
        name: Hal
        type: light
      - entities:
          - entity: light.kitchen_main
          - entity: light.kitchen_coffee_area
          - entity: light.dinning_spots
          - entity: light.living_spots
          - entity: group.living_relax_lights
        title: Verlichting
        type: entities
      - entities:
          - entity: input_boolean.master_bedroom_alarm_enabled
          - entity: input_datetime.master_bedroom_alarm_clock_time
          - entity: input_select.radio_station
        show_header_toggle: false
        title: Master Bedroom Alarm
        type: entities
    icon: ''
    path: bedroom
    title: Bedroom
  - title: New Home Design
    path: new-home-design
    badges: []
    cards:
      - card:
          tap_action:
            action: toggle
          title: Lights ON
          type: entities
        entities:
          - light.bathroom_l3
          - light.bathroom_shower_spots
          - light.bathroom_spots
          - light.cv_room
          - light.carport_flowerbed
          - light.carport_main_light
          - light.carport_night_light
          - light.carport_storage_1
          - light.carport_storage_2
          - light.dad_bedroom_spots
          - light.dinning_l2
          - light.dinning_l3
          - light.dinning_spots
          - light.dressing_spots
          - light.enterance_light
          - light.hallway_lights
          - light.kids_bedroom_l2
          - light.kids_bedroom_spots
          - light.kitchen_coffee_area
          - light.kitchen_l3
          - light.kitchen_main
          - light.living_l2
          - light.living_l3
          - light.living_spots
          - light.master_bathroom_l2
          - light.master_bathroom_l3
          - light.master_bathroom_spots
          - light.master_bedroom_l2
          - light.master_bedroom_l3
          - light.master_bedroom_spots
          - light.office_l2
          - light.office_l3
          - light.office_spots
          - light.stairs_0_1
          - light.stairs_1_2
          - light.terrace
          - switch.dad_bedroom_fan
          - switch.dad_bedroom_s1
          - switch.dad_bedroom_s2
          - switch.dad_bedroom_s3
          - switch.dinning_table
          - switch.kids_bedroom_fan
          - switch.kids_bedroom_s1
          - switch.kids_bedroom_s3
          - switch.kids_bedroom_s4
          - switch.kids_bedroom_window_left
          - switch.living_couch_dinning
          - switch.living_couch_window
          - switch.living_tv_light
          - switch.master_bedroom_s1
          - switch.master_bedroom_s2
          - switch.master_bedroom_s3
          - switch.office_desk_left
          - switch.office_library_left
          - switch.office_s2
        show_empty: false
        state_filter:
          - 'on'
        type: entity-filter
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: weather-forecast
                entity: weather.home
                name: Weer
          - type: vertical-stack
            cards:
              - type: entity-filter
                card:
                  tap_action:
                    action: toggle
                  title: Lights ON
                  type: entities
                  entities:
                    - light.bathroom_l3
                    - light.bathroom_shower_spots
                    - light.bathroom_spots
                    - light.cv_room
                    - light.carport_flowerbed
                    - light.carport_main_light
                    - light.carport_night_light
                    - light.carport_storage_1
                    - light.carport_storage_2
                    - light.dad_bedroom_spots
                    - light.dinning_l2
                    - light.dinning_l3
                    - light.dinning_spots
                    - light.dressing_spots
                    - light.enterance_light
                    - light.hallway_lights
                    - light.kids_bedroom_l2
                    - light.kids_bedroom_spots
                    - light.kitchen_coffee_area
                    - light.kitchen_l3
                    - light.kitchen_main
                    - light.living_l2
                    - light.living_l3
                    - light.living_spots
                    - light.master_bathroom_l2
                    - light.master_bathroom_l3
                    - light.master_bathroom_spots
                    - light.master_bedroom_l2
                    - light.master_bedroom_l3
                    - light.master_bedroom_spots
                    - light.office_l2
                    - light.office_l3
                    - light.office_spots
                    - light.stairs_0_1
                    - light.stairs_1_2
                    - light.terrace
                    - switch.dad_bedroom_fan
                    - switch.dad_bedroom_s1
                    - switch.dad_bedroom_s2
                    - switch.dad_bedroom_s3
                    - switch.dinning_table
                    - switch.kids_bedroom_fan
                    - switch.kids_bedroom_s1
                    - switch.kids_bedroom_s3
                    - switch.kids_bedroom_s4
                    - switch.kids_bedroom_window_left
                    - switch.living_couch_dinning
                    - switch.living_couch_window
                    - switch.living_tv_light
                    - switch.master_bedroom_s1
                    - switch.master_bedroom_s2
                    - switch.master_bedroom_s3
                    - switch.office_desk_left
                    - switch.office_library_left
                    - switch.office_s2
                show_empty: false
                state_filter:
                  - 'on'
custom_header:
  exceptions: []
  compact_mode: true
  chevrons: false
