custom_header:
  chevrons: false
  compact_mode: true
  exceptions: []
  menu_dropdown: false
  shadow: false
resources:
  - type: module
    url: /local/atomic_calendar.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /community_plugin/spotify-card/spotify-card.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/harmony-card/harmony-card.js
  - type: module
    url: /community_plugin/flex-horseshoe-card/flex-horseshoe-card.js
  - type: module
    url: /community_plugin/lovelace-animated-background/animated-background.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: js
    url: >-
      https://raw.githubusercontent.com/gadgetchnnel/lovelace-home-feed-card/master/custom_card.json
  - type: js
    url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: js
    url: /community_plugin/calendar-card/calendar-card.js
  - type: module
    url: /community_plugin/atomic_calendar/atomic_calendar.js
  - type: module
    url: /local/auto-entities.js
title: Van Hoof
views:
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/status.yaml
  - !include /config/lovelace/views/living_area/view.yaml
  - !include /config/lovelace/views/office/office-view.yaml
  - !include /config/lovelace/views/master_bedroom.yaml
  - !include /config/lovelace/views/debug.yaml  
  - !include /config/lovelace/views/chores.yaml