custom_header:
  chevrons: false
  compact_mode: true
  exceptions: []
  menu_dropdown: false
  shadow: false
resources:
  # https://github.com/lukevink/home-assistant-buienradar-forecast-card/blob/master/buien-rain-card.js
  - url: /local/custom_ui/buien-radar/buien-rain-card.js
    type: module

  # https://github.com/maykar/custom-header
  - url: /local/community/custom-header/custom-header.js
    type: module

  # https://github.com/thomasloven/lovelace-auto-entities
  - url: /local/custom_ui/auto-entities/auto-entities.js
    type: module

custom_header:
  compact_mode: true
  kiosk_mode: false
  disable_sidebar: false
  hide_config: false
  hide_help: false
  voice_hide: false
  options_hide: false
  chevrons: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
  exceptions:
    - conditions:
        # user: maykar, Bram Kragten, Ludeeus
        user_agent: Mobile
        media_query: "(max-width: 600px)"
      config:
        #footer_mode: true
        #reverse_button_direction: true
        #reverse_tab_direction: true
        disable_sidebar: true
        voice_hide: true
        options_hide: true
        chevrons: false

title: Van Hoof
views:
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/status.yaml
  - !include /config/lovelace/views/living_area/view.yaml
  - !include /config/lovelace/views/office/office-view.yaml
  - !include /config/lovelace/views/master_bedroom/view-master-bedroom.yaml
  - !include /config/lovelace/views/kids/view-kids.yaml
  - !include /config/lovelace/views/debug/view-debug.yaml  
  - !include /config/lovelace/views/chores.yaml