custom_header:
  chevrons: false
  compact_mode: true
  exceptions: []
  menu_dropdown: false
  shadow: false
resources:
  - type: module
    url: /local/atomic_calendar.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /community_plugin/spotify-card/spotify-card.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/harmony-card/harmony-card.js
  - type: module
    url: /community_plugin/flex-horseshoe-card/flex-horseshoe-card.js
  - type: module
    url: /community_plugin/lovelace-animated-background/animated-background.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: js
    url: >-
      https://raw.githubusercontent.com/gadgetchnnel/lovelace-home-feed-card/master/custom_card.json
  - type: js
    url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: js
    url: /community_plugin/calendar-card/calendar-card.js
  - type: module
    url: /community_plugin/atomic_calendar/atomic_calendar.js
  - type: module
    url: /local/auto-entities.js
title: Van Hoof
views:
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/status.yaml
  - !include /config/lovelace/views/living_area.yaml
  - !include /config/lovelace/views/kantoor.yaml
  - !include /config/lovelace/views/chores.yaml
  - !include /config/lovelace/views/master_bedroom.yaml
  - !include /config/lovelace/views/debug.yaml
  - badges: []
    cards:
      - card:
          title: Lights on
          type: entities
        column_width: calc(100% / 3)
        filter:
          exclude:
            - entity_id: switch.droogkast
            - entity_id: switch.wasmachine
            - domain: light_group
          include:
            - domain: light
              options:
                tap_action:
                  action: toggle
              state: 'on'
            - domain: media_player
              state: playing
        show_empty: false
        sort: 'domain, name'
        type: 'custom:auto-entities'
    path: home-status
    title: Status
  - badges: []
    cards:
      - card:
          title: Lights on
          type: entities
        filter:
          exclude:
            - entity_id: switch.droogkast
            - entity_id: switch.wasmachine
            - domain: light_group
          include:
            - domain: light
              options:
                tap_action:
                  action: toggle
              state: 'on'
            - domain: switch
              options:
                tap_action:
                  action: toggle
              state: 'on'
        show_empty: false
        sort: name
        type: 'custom:auto-entities'
    icon: ''
    path: bedroom
    title: Bedroom
  - badges: []
    cards:
      - card:
          tap_action:
            action: toggle
          title: Lights ON
          type: entities
        entities:
          - light.bathroom_l3
          - light.bathroom_shower_spots
          - light.bathroom_spots
          - light.cv_room
          - light.carport_flowerbed
          - light.carport_main_light
          - light.carport_night_light
          - light.carport_storage_1
          - light.carport_storage_2
          - light.dad_bedroom_spots
          - light.dinning_l2
          - light.dinning_l3
          - light.dinning_spots
          - light.dressing_spots
          - light.enterance_light
          - light.hallway_lights
          - light.kids_bedroom_l2
          - light.kids_bedroom_spots
          - light.kitchen_coffee_area
          - light.kitchen_l3
          - light.kitchen_main
          - light.living_l2
          - light.living_l3
          - light.living_spots
          - light.master_bathroom_l2
          - light.master_bathroom_l3
          - light.master_bathroom_spots
          - light.master_bedroom_l2
          - light.master_bedroom_l3
          - light.master_bedroom_spots
          - light.office_l2
          - light.office_l3
          - light.office_spots
          - light.stairs_0_1
          - light.stairs_1_2
          - light.terrace
          - switch.dad_bedroom_fan
          - switch.dad_bedroom_s1
          - switch.dad_bedroom_s2
          - switch.dad_bedroom_s3
          - switch.dinning_table
          - switch.kids_bedroom_fan
          - switch.kids_bedroom_s1
          - switch.kids_bedroom_s3
          - switch.kids_bedroom_s4
          - switch.kids_bedroom_window_left
          - switch.living_couch_dinning
          - switch.living_couch_window
          - switch.living_tv_light
          - switch.master_bedroom_s1
          - switch.master_bedroom_s2
          - switch.master_bedroom_s3
          - switch.office_desk_left
          - switch.office_library_left
          - switch.office_s2
        show_empty: false
        state_filter:
          - 'on'
        type: entity-filter
      - calendars:
          - calendar.todoist
        entities:
          - sensor.home_commute
          - sensor.to_xant
          - sensor.to_bagaar
        id_filter: ^home_feed_.*
        show_empty: true
        title: Home Feed
        type: 'custom:home-feed-card'
      - artwork: cover
        entity: media_player.living_room
        type: 'custom:mini-media-player'
      - entities:
          - entity: light.alle_lichten
        type: entities
    path: new-home-design
    title: New Home Design
  - badges:
      - entity: binary_sensor.wan
      - entity: binary_sensor.updater
      - entity: sensor.time_utc
      - entity: sensor.date_time_utc
      - entity: sensor.date_time_iso
      - entity: sensor.time
      - entity: sensor.time_date
      - entity: sensor.internet_time
      - entity: sensor.date
      - entity: sensor.date_time
      - entity: sensor.br_symbol
      - entity: sensor.br_pressure
      - entity: sensor.br_humidity
      - entity: sensor.br_temperature
      - entity: sensor.br_wind_speed
      - entity: sensor.wasmachine_total_kwh
      - entity: sensor.wasmachine_volts
      - entity: sensor.wasmachine_amp
      - entity: sensor.wasmachine_today_kwh
      - entity: sensor.wasmachine_watts
      - entity: sensor.droogkast_volts
      - entity: sensor.droogkast_amp
      - entity: sensor.droogkast_today_kwh
      - entity: sensor.droogkast_watts
      - entity: sensor.droogkast_total_kwh
      - entity: sensor.to_bagaar
      - entity: sensor.home_commute
      - entity: sensor.to_xant
      - entity: sensor.sonarr_disk_space
      - entity: sensor.sonarr_upcoming
      - entity: sensor.freenas_disk0_temperature
      - entity: sensor.freenas_disk1_temperature
      - entity: sensor.freenas_disk2_temperature
      - entity: sensor.freenas_disk3_temperature
      - entity: sensor.freenas_space_free
      - entity: sensor.nebula_datasets
      - entity: sensor.freenas_1min_load
      - entity: sensor.freenas_5min_load
      - entity: sensor.freenas_15min_load
      - entity: sensor.freenas_uptime
      - entity: sensor.freenas_cpu_temperature
      - entity: sensor.freenas_cpu_used
      - entity: sensor.dark_sky_summary_0d
      - entity: sensor.dark_sky_summary_0h
      - entity: sensor.dark_sky_icon_0h
      - entity: sensor.dark_sky_temperature_0h
      - entity: sensor.dark_sky_icon_0d
      - entity: sensor.sonarr_wanted
      - entity: sensor.dark_sky_temperature
      - entity: sensor.sonarr_queue
      - entity: sensor.dark_sky_temperature_1h
      - entity: sensor.dark_sky_summary
      - entity: sensor.dark_sky_summary_1h
      - entity: sensor.dark_sky_icon
      - entity: sensor.dark_sky_icon_1h
      - entity: sensor.speedtest_upload
      - entity: sensor.speedtest_download
      - entity: sensor.speedtest_ping
      - entity: sensor.hacs
      - entity: sun.sun
    cards:
      - entity: media_player.living_tv
        type: media-control
      - entity: media_player.living_room
        type: media-control
      - entity: media_player.spotify_michel_van_hoof
        type: media-control
      - entities:
          - person.nicholas
          - person.michel
          - person.alexandra
        show_header_toggle: true
        title: Family
        type: entities
      - entities:
          - entity: light.living_couch_dinning
          - entity: light.living_tv_light
          - entity: light.kitchen_coffee_area
          - entity: light.dinning_table_lamp
        show_header_toggle: true
        title: Sfeerverlichting Living
        type: entities
      - entities:
          - entity: automation.turn_on_kids_week_when_their_tablets_arrive
          - entity: automation.inform_dad_that_kids_week_has_started
          - entity: automation.turn_on_lights_when_i_arrive_home_in_the_dark
          - entity: automation.master_bedroom_wake_up_routine_when_alarm_is_set
          - entity: automation.turn_on_lights_when_i_am_home_and_it_is_getting_dark
        title: Automation
        type: entities
      - entities:
          - calendar.todoist
          - calendar.xylos
          - calendar.kalender_lagere_school
          - calendar.holidays_in_belgium
          - calendar.michel_van_hoof_prive
          - calendar.family
          - calendar.kalender_venstraat
          - calendar.routine_calendar
        title: Calendar
        type: entities
      - entity: camera.buienradar_loop
        type: picture-entity
      - entities:
          - input_boolean.kids_week
          - input_boolean.master_bedroom_alarm_enabled
          - input_boolean.washingmachine_done
          - input_boolean.dryer_done
        title: Input boolean
        type: entities
      - entities:
          - input_datetime.master_bedroom_alarm_clock_time
        title: Input datetime
        type: entities
      - entities:
          - input_number.spotify_volume
        title: Input number
        type: entities
      - entities:
          - input_select.chromecast_radio
          - input_select.dryer_state
          - input_select.radio_station
          - input_select.spotify_playlist
          - input_select.spotify_source
          - input_select.washingmachine_state
        title: Input select
        type: entities
      - entities:
          - light.stairs_0_1
          - light.carport_storage_1
          - light.master_bathroom_l2
          - light.stairs_1_2
          - light.carport_storage_2
          - light.master_bathroom_l3
          - light.living_spots
          - light.dinning_spots
          - light.master_bedroom_spots
          - light.living_l2
          - light.dinning_l2
          - light.master_bedroom_l2
          - light.living_l3
          - light.dinning_l3
          - light.master_bedroom_l3
          - light.bathroom_spots
          - light.kitchen_main
          - light.bathroom_shower_spots
          - light.bathroom_l3
          - light.kitchen_l3
          - light.kids_bedroom_spots
          - light.office_spots
          - light.kids_bedroom_l2
          - light.office_l2
          - light.dad_bedroom_spots
          - light.office_l3
          - light.master_bathroom_spots
          - light.carport_main_light
          - light.dressing_spots
          - light.terrace
          - light.carport_night_light
          - light.cv_room
          - light.enterance_light
          - light.carport_flowerbed
          - light.hallway_lights
        title: Light
        type: entities
      - entity: media_player.living_kodi
        type: media-control
      - entity: media_player.woonkamer
        type: media-control
      - entities:
          - scene.background_lighting_livingroom
        title: Scene
        type: entities
      - entities:
          - script.home_radio
          - script.wake_up_light_masterbedroom
        title: Script
        type: entities
      - entities:
          - switch.kids_bedroom_s1
          - switch.kids_bedroom_window_left
          - switch.kids_bedroom_s3
          - switch.living_couch_dinning
          - switch.kids_bedroom_s4
          - switch.dad_bedroom_fan
          - switch.dad_bedroom_s1
          - switch.dad_bedroom_s2
          - switch.office_desk_left
          - switch.dad_bedroom_s3
          - switch.master_bedroom_s1
          - switch.master_bedroom_s2
          - switch.master_bedroom_s3
          - switch.office_s2
          - switch.office_library_left
          - switch.kids_bedroom_fan
          - switch.droogkast
          - switch.wasmachine
        title: Switch
        type: entities
      - entity: weather.br_unknown_station
        type: weather-forecast
      - entity: weather.dark_sky
        type: weather-forecast
      - entity: weather.thuis
        type: weather-forecast
    path: Generated
    title: Generated
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: weather.thuis
                type: weather-forecast
              - card:
                  show_header_toggle: false
                  show_state: false
                  title: Who is Home
                  type: glance
                entities:
                  - entity: person.michel
                    name: Michel
                  - entity: person.nicholas
                    name: Nicholas
                  - entity: person.alexandra
                    name: Alexandra
                show_empty: false
                state_filter:
                  - home
                type: entity-filter
            type: vertical-stack
          - cards:
              - entities:
                  - entity: sensor.home_commute
                  - entity: sensor.to_xant
                  - entity: sensor.to_bagaar
                  - entity: sensor.speedtest_download
                  - entity: sensor.speedtest_upload
                  - entity: sensor.speedtest_ping
                  - entity: input_boolean.kids_week
                  - entity: input_select.dryer_state
                  - entity: input_select.washingmachine_state
                show_header_toggle: false
                title: Quick Info
                type: entities
            type: vertical-stack
        type: horizontal-stack
      - calendar_days_forward: 3
        calendars:
          - calendar.todoist
        title: Home Feed
        type: 'custom:home-feed-card'
    panel: false
    path: new-home-view
    title: New Home View
