homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_assistant_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_height
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels
  # Customization file
  customize: !include customize.yaml
  
  #auth_providers:
  # - type: trusted_networks
  #   trusted_networks:
  #     - 10.32.1.0/24
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes #!include_dir_merge_list themes/


logger:
  default: warning
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

http:
     #base_url: !secret home_base_url
     use_x_forwarded_for: true
     trusted_proxies:
       - !secret reverse_proxy_ip
     ip_ban_enabled: false
     login_attempts_threshold: 5
  


# Text to speech
tts:
  - platform: google_translate
    language: 'nl'
  - platform: amazon_polly
    region_name: eu-central-1
    voice: Lotte
    text_type: ssml
    aws_access_key_id: !secret AWS_ACCESS_KEY_ID
    aws_secret_access_key: !secret AWS_SECRET_ACCESS_KEY


group: !include groups.yaml
automation: !include automations.yaml
# Also Support manual transformation creation in files for cleaner code
automation old: !include_dir_merge_list Automations/
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
#scene old: !include_dir_merge_named scenes/

speedtestdotnet:

# Cloud
cloud:

google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret
    

#lovelace in yaml style
lovelace:
  mode: yaml
  resources:
    # https://github.com/lukevink/home-assistant-buienradar-forecast-card/blob/master/buien-rain-card.js
    - url: /local/custom_ui/buien-radar/buien-rain-card.js
      type: module

    # https://github.com/atomic7777/atomic_calendar
    - url: /local/custom_ui/atomic-calendar/atomic-calendar.js
      type: module

    # https://github.com/maykar/custom-header
    - url: /local/custom_ui/custom-header/custom-header.js
      type: module

    # https://github.com/thomasloven/lovelace-auto-entities
    - url: /local/custom_ui/auto-entities/auto-entities.js
      type: module

      # https://github.com/kalkih/mini-media-player
    - url: /local/custom_ui/mini-media-player/mini-media-player-bundle.js
      type: module

      # https://github.com/gadgetchnnel/lovelace-home-feed-card/
    - type: js
      url: /local/custom_ui/lovelace-home-feed-card/lovelace-home-feed-card.js

      # https://github.com/custom-cards/button-card
    - type: module
      url: /local/custom_ui/button-card/button-card.js

      # ???
    - type: module
      url: /local/custom_ui/calendar-card/calendar-card.js

    # https://github.com/thomasloven/lovelace-slider-entity-row
    - type: module
      url: /local/custom_ui/lovelace-slider-entity-row/slider-entity-row.js

      # https://github.com/sbryfcz/harmony-card/
    - type: module
      url: /local/custom_ui/harmony-card/harmony-card.js

      # https://github.com/lukevink/home-assistant-buienradar-forecast-card
    - type: module
      url: /local/custom_ui/buien-rain-card/buien-rain-card.js

      # https://github.com/custom-cards/text-element
    - type: module
      url: /local/custom_ui/text-element/text-element.js

      # https://github.com/thomasloven/lovelace-gui-sandbox
    - type: module
      url: /local/custom_ui/gui-sandbox/gui-sandbox.js
   
      # https://github.com/custom-cards/upcoming-media-card
    - type: module
      url: /local/custom_ui/upcoming-media-card/upcoming-media-card.js

# Discover some devices automatically
discovery:

# Media Players
media_player: !include_dir_merge_list mediaplayers/

# My KNX Config
knx: !include_dir_merge_list knx/
#KNX Lights
light: !include_dir_merge_list lights/
switch: !include_dir_merge_list switches/
## Include all my inputs
#TODO: move to seperate folders
input_select: !include_dir_merge_named input/select/
input_number: !include_dir_merge_named input/number/
input_text: !include_dir_merge_named input/text/
input_boolean: !include_dir_merge_named input/boolean/
input_datetime: !include_dir_merge_named input/datetime/
# Sensors
sensor: !include_dir_merge_list sensors/integrations/
binary_sensor: !include_dir_merge_list sensors/binary/
# Device trackers we are using
device_tracker: !include_dir_merge_list device_trackers/

zone: !include_dir_merge_list zones/
persistent_notification:
# Example configuration.yaml entry
#DISABLED Sabnzbd for now since not working
#sabnzbd: !include integrations/media/sabnzbd.yaml

tplink: !include integrations/tp-link/tp-link.yaml
remote: !include integrations/harmony.yaml

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
  - platform: buienradar


camera:
  - platform: buienradar
    country_code: BE
    
spotify:
  client_id: !secret SPOTIFY_CLIENT_ID
  client_secret: !secret SPOTIFY_CLIENT_SECRET

influxdb:
  host: !secret influx_host
  port: 8086
  database: !secret influx_database
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  tags:
    instance: !secret instance
    source: hass

calendar: !include integrations/todoist.yaml
# Removing it from config and trying in the UI first
mqtt:
  discovery: true
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password
  client_id: home-assistant-prd

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password


proximity: !include_dir_merge_list proximity/

# TODO:
# https://www.home-assistant.io/integrations/opnsense/
# https://www.home-assistant.io/integrations/device_tracker.mqtt/
# https://www.home-assistant.io/integrations/mqtt_room/
# https://www.home-assistant.io/integrations/zabbix/
# https://www.home-assistant.io/integrations/bayesian/
# https://www.home-assistant.io/integrations/almond/
# https://www.home-assistant.io/integrations/google_assistant/
# https://www.home-assistant.io/integrations/conversation/
# https://www.home-assistant.io/integrations/system_health/
